import 'package:flutter/material.dart';
import '../models/order_model.dart';
import '../models/cart_item_model.dart';
import '../repositories/order_repository.dart';

/// Manages checkout flow state.
/// Steps: customer info → shipping → payment → confirmation.
class CheckoutViewModel extends ChangeNotifier {
  final MockOrderRepository _repo;

  // ── Form Fields ───────────────────────────────────────────────────────────
  String _customerName = '';
  String _customerPhone = '';
  String _address = '';
  String _province = '';
  String _district = '';
  String _ward = '';
  String _note = '';
  String _paymentMethod = 'COD';
  int _currentStep = 0;

  // ── State ──────────────────────────────────────────────────────────────────
  bool _isLoading = false;
  OrderModel? _placedOrder;
  String? _error;

  CheckoutViewModel(this._repo);

  // ── Getters ───────────────────────────────────────────────────────────────
  String get customerName => _customerName;
  String get customerPhone => _customerPhone;
  String get address => _address;
  String get province => _province;
  String get district => _district;
  String get ward => _ward;
  String get note => _note;
  String get paymentMethod => _paymentMethod;
  int get currentStep => _currentStep;
  bool get isLoading => _isLoading;
  OrderModel? get placedOrder => _placedOrder;
  String? get error => _error;

  /// Full shipping address assembled from parts.
  String get fullShippingAddress {
    final parts = [_address, _ward, _district, _province]
        .where((s) => s.isNotEmpty)
        .toList();
    return parts.join(', ');
  }

  // ── Pre-fill from user profile ────────────────────────────────────────────
  void prefillFromUser({
    required String name,
    required String phone,
    String? address,
    String? province,
    String? district,
    String? ward,
  }) {
    _customerName = name;
    _customerPhone = phone;
    _address = address ?? '';
    _province = province ?? '';
    _district = district ?? '';
    _ward = ward ?? '';
    notifyListeners();
  }

  // ── Setters ───────────────────────────────────────────────────────────────
  void setCustomerName(String v) { _customerName = v; notifyListeners(); }
  void setCustomerPhone(String v) { _customerPhone = v; notifyListeners(); }
  void setAddress(String v) { _address = v; notifyListeners(); }
  void setProvince(String v) { _province = v; notifyListeners(); }
  void setDistrict(String v) { _district = v; notifyListeners(); }
  void setWard(String v) { _ward = v; notifyListeners(); }
  void setNote(String v) { _note = v; notifyListeners(); }
  void setPaymentMethod(String v) { _paymentMethod = v; notifyListeners(); }

  // ── Navigation ────────────────────────────────────────────────────────────
  void nextStep() {
    if (_currentStep < 2) {
      _currentStep++;
      notifyListeners();
    }
  }

  void prevStep() {
    if (_currentStep > 0) {
      _currentStep--;
      notifyListeners();
    }
  }

  void goToStep(int step) {
    _currentStep = step;
    notifyListeners();
  }

  // ── Place Order ───────────────────────────────────────────────────────────
  Future<OrderModel?> placeOrder({
    required String userId,
    required List<CartItemModel> cartItems,
    required double subtotal,
    required double shippingFee,
  }) async {
    _isLoading = true;
    _error = null;
    notifyListeners();

    try {
      final order = OrderModel(
        id: '', // Will be generated by repo
        userId: userId,
        items: List.from(cartItems),
        subtotal: subtotal,
        shippingFee: shippingFee,
        total: subtotal + shippingFee,
        status: OrderStatus.pending,
        customerName: _customerName,
        customerPhone: _customerPhone,
        shippingAddress: fullShippingAddress,
        note: _note.isEmpty ? null : _note,
        paymentMethod: _paymentMethod,
        createdAt: DateTime.now(),
      );

      _placedOrder = await _repo.placeOrder(order);
      _isLoading = false;
      notifyListeners();
      return _placedOrder;
    } catch (e) {
      _error = 'Đặt hàng thất bại: ${e.toString()}';
      _isLoading = false;
      notifyListeners();
      return null;
    }
  }

  // ── Reset ─────────────────────────────────────────────────────────────────
  void reset() {
    _currentStep = 0;
    _note = '';
    _paymentMethod = 'COD';
    _placedOrder = null;
    _error = null;
    notifyListeners();
  }
}
