import 'package:flutter/material.dart';
import '../models/order_model.dart';
import '../models/order_model.dart';
import '../models/cart_item_model.dart';
import '../models/address_model.dart';
import '../repositories/order_repository.dart';
import 'auth_viewmodel.dart';

/// Manages checkout flow state.
/// Steps: customer info → shipping → payment → confirmation.
class CheckoutViewModel extends ChangeNotifier {
  final OrderRepository _repo;

  // ── Form Fields ───────────────────────────────────────────────────────────
  // ── Form Fields ───────────────────────────────────────────────────────────
  AddressModel? _selectedAddress;
  String _note = '';
  String _paymentMethod = 'COD';

  // ── State ──────────────────────────────────────────────────────────────────
  bool _isLoading = false;
  OrderModel? _placedOrder;
  String? _error;

  CheckoutViewModel(this._repo);

  // ── Getters ───────────────────────────────────────────────────────────────
  // ── Getters ───────────────────────────────────────────────────────────────
  AddressModel? get selectedAddress => _selectedAddress;
  String get note => _note;
  String get paymentMethod => _paymentMethod;
  bool get isLoading => _isLoading;
  OrderModel? get placedOrder => _placedOrder;
  String? get error => _error;

  // ── Setters ───────────────────────────────────────────────────────────────
  void setSelectedAddress(AddressModel address) {
    _selectedAddress = address;
    notifyListeners();
  }

  void setNote(String value) {
    _note = value;
    notifyListeners();
  }

  void setPaymentMethod(String method) {
    _paymentMethod = method;
    notifyListeners();
  }

  // ── Prefill ───────────────────────────────────────────────────────────────
  void prefillFromUser(AuthViewModel authVM) {
    final user = authVM.currentUser;
    if (user != null && user.addresses.isNotEmpty) {
      // Tìm địa chỉ default, nếu không có thì lấy cái đầu tiên
      _selectedAddress = user.addresses.firstWhere(
        (a) => a.isDefault,
        orElse: () => user.addresses.first,
      );
    }
    notifyListeners();
  }

  // ── Place Order ───────────────────────────────────────────────────────────
  // ── Place Order ───────────────────────────────────────────────────────────
  Future<OrderModel?> placeOrder({
    required String userId,
    required List<CartItemModel> cartItems,
    required double subtotal,
    required double shippingFee,
  }) async {
    _isLoading = true;
    _error = null;
    notifyListeners();

    try {
      // Thanh toán online (Momo, VNPay) → status = paid
      // COD → status = pending (chờ thanh toán khi nhận hàng)
      final isOnlinePayment = _paymentMethod == 'Momo' || _paymentMethod == 'VNPay';

      final order = OrderModel(
        id: '', // Will be generated by repo
        userId: userId,
        items: List.from(cartItems),
        subtotal: subtotal,
        shippingFee: shippingFee,
        total: subtotal + shippingFee,
        status: isOnlinePayment ? OrderStatus.paid : OrderStatus.pending,
        customerName: _selectedAddress?.name ?? 'Khách hàng',
        customerPhone: _selectedAddress?.phone ?? '',
        shippingAddress: _selectedAddress?.fullAddress ?? '',
        note: _note.isEmpty ? null : _note,
        paymentMethod: _paymentMethod,
        createdAt: DateTime.now(),
      );

      _placedOrder = await _repo.placeOrder(order);
      _isLoading = false;
      notifyListeners();
      return _placedOrder;
    } catch (e) {
      _error = 'Đặt hàng thất bại: ${e.toString()}';
      _isLoading = false;
      notifyListeners();
      return null;
    }
  }

  // ── Reset ─────────────────────────────────────────────────────────────────
  void reset() {
    _note = '';
    _paymentMethod = 'COD';
    _placedOrder = null;
    _error = null;
    notifyListeners();
  }
}
