// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpH-S4YW5_SPE6o5eUyZIUQ23GDKIbHTI',
    appId: '1:92836567231:web:59c703c80986d1c32b0e0a',
    messagingSenderId: '92836567231',
    projectId: 'laptophub-70e6e',
    authDomain: 'laptophub-70e6e.firebaseapp.com',
    storageBucket: 'laptophub-70e6e.firebasestorage.app',
    measurementId: 'G-WYRYPPZ9X0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmFkNbYI9XPA3cjKipLDihqllY2CwxOuM',
    appId: '1:92836567231:android:d9977539b9e1604f2b0e0a',
    messagingSenderId: '92836567231',
    projectId: 'laptophub-70e6e',
    storageBucket: 'laptophub-70e6e.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCpH-S4YW5_SPE6o5eUyZIUQ23GDKIbHTI',
    appId: '1:92836567231:web:2feb3ef85fc896462b0e0a',
    messagingSenderId: '92836567231',
    projectId: 'laptophub-70e6e',
    authDomain: 'laptophub-70e6e.firebaseapp.com',
    storageBucket: 'laptophub-70e6e.firebasestorage.app',
    measurementId: 'G-4FHQNEYK8B',
  );
}
